Project Submission
Chrissiku/Budget-app pull request #4
Opened 2022-10-13 12:11 UTC by Chrissiku

## What I did ♻️ 
> In this project I implement the required features to set up and deploy a Budget-app that can help users manage their expenses professionally.

You can learn more by clicking on the link below

### Link to the Video : [Loom video](https://www.loom.com/share/fb10c51245ce455cbc859e4e8a64eebf)

## Project requirements 📗 

### Design
- You should follow these [design guidelines](https://www.behance.net/gallery/19759151/Snapscan-iOs-design-and-branding?tracking_source=), including:
  - Colors.
  - Typography: font face, size and weight.
  - Layout: composition and space between elements.

> NOTE: In these design guidelines there are several UIs that you won't need for this exercise; also, some pages are not given a design and you will create them following the design guidelines of the other pages.

Original design idea by [Gregoire Vella on Behance](https://www.behance.net/gregoirevella).

The [Creative Commons license of the design](https://creativecommons.org/licenses/by-nc/4.0/) requires that you give appropriate credit to the author. Therefore, you must do it in the README of your project.

### Interactions
- Splash screen
  - A simple page with the name of your app (yes, you need to choose one), and links to the sign up and log in pages.

- Sign up and log in pages
  - The user should be able to register in the app with full name, email and password (all mandatory).
  - The user can log into the app using email and password.
  - If the user is not logged in, they can't access pages that require the user to be logged in (all the pages described below).

- Home page (catagories page)
  - When the user logs in, they are presented with the categories page.
  - For each category, the user can see their name, icon and the total amount of all the transactions that belongs to that category.
  - When the user clicks (or taps) on a category item, the application navigates to the transactions page for that category.
  - There is a button "add a new category" at the bottom that brings the user to the page to create a new category.

- Transactions page
  - For a given category, the list of transactions is presented, ordered by the most recent.
  - At the top of the page the user could see the total amount for the category (sum of all of the amounts of the transactions in that category).
  - There is a button "add a new transaction" at the bottom that brings the user to the page to create a new transaction.
  - When the user clicks on the "Back" button (<), the user navigates to the home page.

- "Add a new category" page
  - The user fills out a form to create a new category, indicating their name and icon (both mandatory).
  - The user click (or taps) the "Save" button to create the new category, and is taken to the home page on success.
  - When the user clicks on the "Back" button (<), the user navigates to the home page.

- "Add a new transaction" page
  - The user fills out a form to create a new transaction with:
    - name (mandatory)
    - amount (mandatory)
    - categories (mandatory at least one)
  - The user click (or taps) the "Save" button to create the new transation, and is taken to the transactions page for that category.
  - When the user clicks on the "Back" button (<), the user navigates to the transactions page for that category.

### Testing requirements
- Create unit and integration tests for all the most important components of your RoR application.

### Technical requirements

- You should use Postgres as your database.
- You should use devise for authentication.
- You should validate all user input to make sure that anyone with bad intentions cannot compromise your app.
- You can use a view template engine of your choice (.erb, .slim, .haml).
- The project should be deployed and accessible online.
- Your database schema should reflect the following structure:

2022-10-13 12:46 UTC, medaminedev66 requested changes
Hi @Chrissiku  😃, :wave:, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- The repo looks professional.
- You have a descriptive PR.
- Your project works as expected and runs without errors.
- Highly organized/clean code.

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-13 12:46 UTC, medaminedev66 commented on app/views/entities/new.html.erb
> +<% end %>
- [ ]  The form is missing a field where users can select the categories to which the transaction should belong. Kindly add a field to the form that allows the user to choose at least one category (the user should be able to choose more than one category).

2022-10-13 12:46 UTC, medaminedev66 commented on spec/requests/entities_spec.rb
> +end
[OPTIONAL] It would be preferable to add some integration tests to assert that the web app works as expected.

2022-10-13 13:34 UTC, Chrissiku commented on app/views/entities/new.html.erb
> +<% end %>
Hello @medaminedev66, I thank you for the review performed on my project.

As said in the project's requirement (Project documentation) that we should also highlight some interesting pieces of code or something you built that we are very proud of.


![Proud of](https://user-images.githubusercontent.com/101924220/195610356-db0e5512-0388-459c-b21c-17ec98d6a055.PNG)

On my side, I set up the project transaction in a way that users don't have to select again a categories when adding a new transaction.
They just have to click on a concerned category and from there they can Add a bunch of transactions to that category.

As shown in the video link below : 
[Video link](https://www.loom.com/share/8bf749d619cd41709f7fcc0265702580)

Thank you for testing that feature so that we can move forward.
Cheer and hope to hear from you soon.

2022-10-13 14:09 UTC, medaminedev66 commented on app/views/entities/new.html.erb
> +<% end %>
Hi @Chrissiku, I understand that you want to create something that interests you even though it does not follow to the project's guidelines. But as a developer, you are asked to follow the requirements of the project.

For better comprehension, the relationship between categories and transactions is a many-to-many relationship, and that means that the transaction can belong to many categories.

As required in the project requirements, the user should be able to fill out a form with name (mandatory), amount (mandatory), and categories (mandatory at least one) to create a new transaction.

2022-10-14 09:02 UTC, omarsalem7 requested changes
Hi @Chrissiku , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![Almost near](https://media.giphy.com/media/ReyD4OdRiHeLDCRaEP/giphy.gif)

 ## Highlights
✔️ Descriptive pull request

 ## Required Changes ♻️

- [x] As stated by the previous reviewer, kindly make sure to add a field (dropdown) when the user creates the transaction, he/she can choose the category related to this transaction.  



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-14 11:07 UTC, OLIPLICHE approved these changes
Hi @Chrissiku, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# Highlights
- Nice for implementing the change, the App is working fine 👏 👏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-14 11:11 UTC, merged

2022-10-14 11:12 UTC, Chrissiku commented
Thank you @OLIPLICHE and thank to @omarsalem7 and @medaminedev66 for the constructive feedback.